source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'JXFrame_Example' do
  pod 'JXFrame', :path => '../'

  target 'JXFrame_Tests' do
    inherit! :search_paths

    
  end
end
